{
  "comments": [
    {
      "key": {
        "uuid": "9fdfeff1_434e816f",
        "filename": "zuul/model.py",
        "patchSetId": 3
      },
      "lineNbr": 735,
      "author": {
        "id": 16068
      },
      "writtenOn": "2019-02-27T21:54:08Z",
      "side": 1,
      "message": "We could break out of the loop after the adjustment.",
      "revId": "8e09a758cf953bc7fdc9f46c70465b671d7cbd1e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}