{
  "comments": [
    {
      "key": {
        "uuid": "3f4b6375_13fd013a",
        "filename": "tests/unit/test_scheduler.py",
        "patchSetId": 1
      },
      "lineNbr": 2522,
      "author": {
        "id": 4146
      },
      "writtenOn": "2017-10-18T22:36:36Z",
      "side": 1,
      "message": "Might be worth a comment here explaining the test is checking that we don\u0027t end up with a second event because the second and first have been merged together resulting in a single event?\n\nThe significance of this might be easy to overlook.",
      "range": {
        "startLine": 2522,
        "startChar": 68,
        "endLine": 2522,
        "endChar": 69
      },
      "revId": "90ca5b5ba2285df966616608d4be50b382cbb2dc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3f4b6375_13762108",
        "filename": "zuul/lib/queue.py",
        "patchSetId": 1
      },
      "lineNbr": 65,
      "author": {
        "id": 4146
      },
      "writtenOn": "2017-10-18T22:36:36Z",
      "side": 1,
      "message": "We\u0027ll only wait if there are no items in the queue. When that happens we get the IndexError. Do you want to move this line into the exception handler to make that more explicit?",
      "range": {
        "startLine": 65,
        "startChar": 16,
        "endLine": 65,
        "endChar": 37
      },
      "revId": "90ca5b5ba2285df966616608d4be50b382cbb2dc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}