{
  "comments": [
    {
      "key": {
        "uuid": "9fb8cfa7_fe5e5374",
        "filename": "tests/unit/test_v3.py",
        "patchSetId": 5
      },
      "lineNbr": 2688,
      "author": {
        "id": 5263
      },
      "writtenOn": "2019-06-10T19:11:21Z",
      "side": 1,
      "message": "The unit test job for Python 3.6 timed out here under Ansible 2.8... does it need increasing, or is it an indication something\u0027s still wrong with the test changes?",
      "revId": "c8f6b7b9b103d620cedea5d5049a9bb1a32fc4fc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9fb8cfa7_29391fa3",
        "filename": "tests/unit/test_v3.py",
        "patchSetId": 5
      },
      "lineNbr": 2721,
      "author": {
        "id": 5263
      },
      "writtenOn": "2019-06-10T14:17:48Z",
      "side": 1,
      "message": "Interesting. Can we create a file under zuul.executor.work_root to read in to work around this? The point of password_read_good was just to make sure the password lookup is able to read from an existing file at a path we\u0027re already allowing.",
      "revId": "c8f6b7b9b103d620cedea5d5049a9bb1a32fc4fc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}